[tool.poetry]
name = "EyeTrackVR"
version = "0.1.7.2"
description = "Opensource, affordable VR eye tracker for VRChat"
authors = ["RedHawk989"]
license = "MIT"
repository = "https://github.com/RedHawk989/EyeTrackVR"

[tool.poetry.dependencies]
python = "~3.11.0"
python-osc = "^1.8.0"
opencv-python = "^4.6.0.66"
numpy = "^1.23.4"
pye3d = "^0.3.1.post1"
requests = "^2.28.1"
pysimplegui = "^4.60.4"
pydantic = "^1.10.2"
win10toast_click = "^0.1.2"
beautifulsoup4 = "^4.11.1"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pyinstaller = "^5.6.2"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
